name: Build and Push Docker Images

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: chanduakhil123  # Hardcoded username
          password: ${{ secrets.DOCKER_PASSWORD }} # Only needs password secret

      # 2. Build & Push Backend
      - name: Build Backend
        uses: docker/build-push-action@v5
        with:
          context: ./eventmanagebackend
          push: true
          tags: chanduakhil123/event-manager-backend:latest

      # 3. Build & Push Frontend
      - name: Build Frontend
        uses: docker/build-push-action@v5
        with:
          context: "./event-manager frontend"
          push: true
          tags: chanduakhil123/event-manager-frontend:latest